apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: recommendation-storage
