apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservation-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: reservation-storage
