apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  ports:
  - name: jaeger-14269
    port: 14269
    targetPort: 14269
  - name: jaeger-5778
    port: 5778
    targetPort: 5778
  - name: jaeger-14268
    port: 14268
    targetPort: 14268
  - name: jaeger-14267
    port: 14267
    targetPort: 14267
  - name: jaeger-16686
    port: 16686
    targetPort: 16686
  - name: jaeger-5775
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: jaeger-6831
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-6832
    port: 6832
    protocol: UDP
    targetPort: 6832
  selector:
    io.kompose.service: jaeger
status:
  loadBalancer: {}
